executable = condor_trk.sh
arguments = $(ClusterID) $(ProcId) $(PLATENUMBER)
output = output/trk.$(ClusterId).$(PLATENUMBER).out
error = error/trk.$(ClusterId).$(PLATENUMBER).err
log = log/trk.$(ClusterId).log
+JobFlavour = "testmatch"
request_memory = 12GB
notification = Never
requirements = (OpSysAndVer =?= "AlmaLinux9")
requirements = Machine =!= LastRemoteHost
on_exit_remove          = (ExitBySignal == False) && ((ExitCode == 1) || (ExitCode == 0))
max_retries             = 3
queue