executable = condor_all.sh
arguments = $(ClusterID) $(ProcId)
output = output/all.$(ClusterId).out
error = error/all.$(ClusterId).err
log = log/all.$(ClusterId).log
+JobFlavour = "longlunch"
request_memory = 4GB
notification = Never
requirements = (OpSysAndVer =?= "AlmaLinux9")
requirements = Machine =!= LastRemoteHost
on_exit_remove          = (ExitBySignal == False) && ((ExitCode == 1) || (ExitCode == 0))
max_retries             = 3
queue