executable = condor_make.sh
arguments = $(ClusterID) $(ProcId) $(CELL)
output = output/make.$(ClusterId).out
error = error/make.$(ClusterId).err
log = log/make.$(ClusterId).log
+JobFlavour = "espresso"
request_memory = 1GB
notification = Never
requirements = (OpSysAndVer =?= "AlmaLinux9")
requirements = Machine =!= LastRemoteHost
on_exit_remove          = (ExitBySignal == False) && ((ExitCode == 1) || (ExitCode == 0))
max_retries             = 2
queue