executable = condor_make.sh
arguments = $(ClusterID) $(ProcId) $(CELL)
output = output/proc.$(ClusterId).$(PLATENUMBER).out
error = error/proc.$(ClusterId).$(PLATENUMBER).err
log = log/proc.$(ClusterId).log
+JobFlavour = "espresso"
notification = Never
requirements = (OpSysAndVer =?= "AlmaLinux9")
requirements = Machine =!= LastRemoteHost
on_exit_remove          = (ExitBySignal == False) && ((ExitCode == 1) || (ExitCode == 0))
max_retries             = 2
queue