executable = condor_tracking.sh
arguments = $(ClusterID) $(ProcId) $(CELL)
output = output/trk.$(ClusterId).$(CELL).out
error = error/trk.$(ClusterId).$(CELL).err
log = log/trk.$(ClusterId).log
+JobFlavour = "longlunch"
request_memory = 32GB
notification = Never
requirements = (OpSysAndVer =?= "AlmaLinux9")
requirements = Machine =!= LastRemoteHost
on_exit_remove          = (ExitBySignal == False) && ((ExitCode == 1) || (ExitCode == 0))
max_retries             = 3
queue